stages:
  creation:
    cmd: python src/creation/run.py \
      --output ${output_creation} \
      --report ${report_params_creation}
    deps:
      - src/creation/run.py
    outs:
      - ${output_creation}
      - ${report_params_creation}
